<!ELEMENT r ( lics, e+ ) >

<!ATTLIST r id CDATA #IMPLIED >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
          xml:lang (smn) #REQUIRED >



<!ELEMENT lics ( lic, ref*, sourcenote* )  >
<!ATTLIST lics xml:space (default|preserve) 'preserve' >

<!ELEMENT lic (#PCDATA|a)* >
<!ATTLIST lic xml:lang (en) #IMPLIED >

<!ELEMENT ref (#PCDATA|a|i)* >
<!ELEMENT sourcenote (#PCDATA|a)* >

<!ELEMENT a ( #PCDATA ) >

<!ELEMENT e ( lg, mg+, ig* ) >
<!ATTLIST e id CDATA #IMPLIED >
<!ATTLIST e mc CDATA #IMPLIED >
<!ATTLIST e src CDATA #IMPLIED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adp | Adv | CC | CS | Clt | Interj | 
                  N | Num | Pcle | Phrase | Po | Pr | Pron | Qu | V | X )
		  #IMPLIED >
<!ATTLIST l spec ( NomAg ) #IMPLIED >
<!ATTLIST l sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >
<!ATTLIST l t_type ( Phrase ) #IMPLIED >
<!ATTLIST l sg1 CDATA #IMPLIED >
<!ATTLIST l sg3 CDATA #IMPLIED >
<!ATTLIST l pl3 CDATA #IMPLIED >
<!ATTLIST l gen CDATA #IMPLIED >
<!ATTLIST l ill CDATA #IMPLIED >
<!ATTLIST l sg_gen CDATA #IMPLIED >
<!ATTLIST l sg_ill CDATA #IMPLIED >
<!ATTLIST l pl_gen CDATA #IMPLIED >
<!ATTLIST l pl_ill CDATA #IMPLIED >
<!ATTLIST l g_stem CDATA #IMPLIED >
<!ATTLIST l v_type CDATA #IMPLIED >
<!ATTLIST l attr CDATA #IMPLIED >
<!ATTLIST l status CDATA #IMPLIED >
<!ATTLIST l hid CDATA #IMPLIED >

<!ELEMENT lg ( l, stem*, analysis*, mini_paradigm*, algu? ) >
<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >
<!ELEMENT wordform (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >

<!ELEMENT mg ( tg ) >
<!ATTLIST mg rest CDATA #IMPLIED >

<!ELEMENT syn ( #PCDATA ) >
<!ELEMENT syng ( syn+ ) >

<!-- Idiom phrases, faste uttrykk -->
<!ELEMENT ig ( i+, id?, it+)+ >
<!ELEMENT i (#PCDATA) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT it (#PCDATA) >


<!-- tg translation group -->

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Abbr | Adp | Adv | CC | CS | Clt | Cp | Det | Interj | 
                  N | Num | Pcle | Po | Pr | Pron | V | X 
) #IMPLIED >
<!ATTLIST t t_type NMTOKEN #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >
<!ATTLIST t tt_auto CDATA #IMPLIED >
<!ATTLIST t rest CDATA #IMPLIED >
<!ATTLIST t l_par CDATA #IMPLIED >

<!ELEMENT tg ( re | syng | t | xg )* >
<!ATTLIST tg xml:lang ( fin ) #REQUIRED >
<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

